// Catalogue source du site : chaque objet represente un produit exploitable partout.
const products = [
  {
    id: "arachide-caramelisee",
    name: "Arachide caramélisée",
    category: "Épicerie",
    priceValue: 7,
    unitMode: "count",
    unitLabel: "pièce",
    image: "images/arachide-caramelisee.png",
    description: "Arachides croquantes enrobées d'un caramel doré, parfaites pour une pause gourmande.",
    origin: "Spécialité maison du chef",
    availability: "Disponible selon le stock en boutique.",
    orderNote: "Produit vendu en bouteille.",
    tip: "Ideal a offrir, a partager ou a servir avec une boisson chaude."
  },
  {
    id: "jus-de-gingembre",
    name: "Jus de gingembre",
    category: "Boissons",
    priceValue: 7,
    unitMode: "count",
    unitLabel: "bouteille",
    image: "images/jus de gingembre.webp",
    description: "Boisson tonique et parfumée, pratique à servir fraîche.",
    origin: "Spécialité maison du chef",
    storage: "A conserver au frais.",
    availability: "Disponible selon stock.",
    orderNote: "Produit vendu à la bouteille. Choisissez le nombre souhaite avant l'ajout au panier.",
    tip: "A servir très frais."
  },
  {
    id: "huile-de-palme",
    name: "Huile de palme",
    category: "Épicerie",
    priceValue: 7.9,
    unitMode: "count",
    unitLabel: "bouteille",
    image: "images/huile-palme.png",
    description: "Huile de palme pour recettes traditionnelles, sauces et plats familiaux.",
    origin: "Cameroun.",
    storage: "A conserver à l'abri de la chaleur et de la lumière.",
    availability: "Disponible selon le stock du jour.",
    orderNote: "Produit vendu à la bouteille. Choisissez le nombre souhaite avant l'ajout au panier.",
    tip: "Base utile pour plusieurs recettes africaines."
  },
  {
    id: "avocat",
    name: "Avocat",
    category: "Fruits",
    priceValue: 7,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/avocat.jfif",
    description: "Avocat fondant, pratique pour salades, tartines, sauces et plats maison.",
    origin: " Mexique",
    storage: "A conserver à temperature ambiante.",
    availability: "Disponible selon arrivage.",
    orderNote: "Produit vendu au kilo.",
    tip: "Parfait pour un guacamole, une salade ou un accompagnement frais."
  },
  {
    id: "mangue",
    name: "Mangue",
    category: "Fruits",
    priceValue: 8,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/mangue togo.webp",
    description: "Mangue parfumée et juteuse, agreable à déguster nature ou en dessert.",
    origin: "Togo.",
    storage: "A laisser murir à température ambiante puis à garder au frais.",
    availability: "Disponible selon saison.",
    orderNote: "Produit vendu au kilo.",
    tip: "Très bonne en smoothie, salade de fruits ou coulis maison."
  },
  {
    id: "ananas",
    name: "Ananas",
    category: "Fruits",
    priceValue: 5.5,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/Ananas du bénin.webp",
    description: "Ananas parfumé, sucre et genereux, agréable nature, en jus ou en dessert.",
    origin: "Bénin.",
    storage: "A temperature ambiante puis au frais apres decoupe.",
    availability: "Disponible selon le stock du jour.",
    orderNote: "Produit vendu au kilo. Indiquez le poids souhaite avant l'ajout au panier.",
    tip: "Très apprécié pour les jus frais et salades de fruits."
  },
  {
    id: "fruit-de-la-passion",
    name: "Fruit de la passion",
    category: "Fruits",
    priceValue: 2,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/fruit de la passion.jfif",
    description: "Fruit parfumé et acidulé, idéal en jus, dessert ou coulis.",
    origin: "Réunion.",
    storage: "A conserver au frais apres maturation.",
    availability: "Disponible selon saison.",
    orderNote: "Produit vendu au kilo. Indiquez le poids souhaite avant l'ajout au panier.",
    tip: "Excellent pour parfumer un yaourt, un dessert ou une boisson."
  },
  {
    id: "plantin-vert-colombie",
    name: "Plantain vert Colombie",
    category: "Fruits",
    priceValue: 2.5,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/Plantains verts en grappe.png",
    description: "Plantain vert de Colombie, apprécié pour fritures, chips ou accompagnements.",
    origin: "Colombie.",
    storage: "A conserver à temperature ambiante.",
    availability: "Disponible selon arrivage.",
    orderNote: "Produit vendu au kilo. Indiquez le poids souhaite avant l'ajout au panier.",
    tip: "Très pratique en cuisson salée."
  },
  {
    id: "banane-plantain-colombie",
    name: "Banane plantain Colombie",
    category: "Fruits",
    priceValue: 2.89,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/Bananes mûres en grappe sur fond blanc.png",
    description: "Plantain de Colombie, apprecié pour sa tenue à la cuisson et son goût généreux.",
    origin: "Colombie.",
    storage: "A conserver à temperature ambiante.",
    availability: "Disponible selon arrivage.",
    orderNote: "Produit vendu au kilo. Indiquez le poids souhaité avant l'ajout au panier.",
    tip: "Très pratique pour alloco, purée ou accompagnement."
  },
  {
    id: "bananes-vertes",
    name: "Bananes vertes",
    category: "Fruits",
    priceValue: 1.9,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/bananes-vertes.png",
    description: "Bananes vertes en grappe, à laisser mûrir selon la texture et la douceur souhaitées.",
    origin: "Origine selon arrivage.",
    storage: "À conserver à température ambiante jusqu'à maturation.",
    availability: "Disponibles selon arrivage.",
    orderNote: "Produit vendu au kilo. Indiquez le poids souhaité avant l'ajout au panier.",
    tip: "Conservez-les à température ambiante et surveillez leur couleur pour choisir leur maturité."
  },
  {
    id: "Mini-bananes",
    name: "Mini-bananes",
    category: "Fruits",
    priceValue: 4.5,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/Bananes mûres et vertes côte à côte.png",
    description: "Mini-bananes douces et savoureuses, faciles à déguster nature ou en dessert.",
    origin: "Colombie.",
    storage: "A conserver à temperature ambiante jusqu'à maturation, puis au frais.",
    availability: "Disponible selon arrivage.",
    orderNote: "Produit vendu au kilo. Indiquez le poids souhaité avant l'ajout au panier.",
    tip: "Très agréables au petit-déjeuner, en collation ou dans une salade de fruits."
  },
  {
    id: "banane-plantin-martinique",
    name: "Banane plantain Martinique",
    category: "Fruits",
    priceValue: 6.5,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/Bananes plantains vert-jaune en grappe.png",
    description: "Banane plantain savoureuse, idéale pour les cuissons poelées, frites ou mijotées.",
    origin: "Martinique.",
    storage: "A conserver à temperature ambiante jusqu'à utilisation.",
    availability: "Disponible selon arrivage.",
    orderNote: "Produit vendu au kilo.",
    tip: "Se cuisine aussi bien en version salée qu'en accompagnement."
  },
  {
    id: "gingembre-frais",
    name: "Gingembre frais",
    category: "Épices",
    priceValue: 7.9,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/gingembre-frais.png",
    description: "Gingembre frais au goût puissant, utile en jus, infusion, marinade ou cuisine.",
    origin: "Pérou.",
    storage: "A conserver au frais pour prolonger la fraîcheur.",
    availability: "Disponible selon arrivage.",
    orderNote: "Produit vendu au kilo.",
    tip: "Peut être rapé, infusé ou mixé selon l'usage."
  },
  {
    id: "curcuma",
    name: "Curcuma",
    category: "Épices",
    priceValue: 12,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/curcuma.png",
    description: "Curcuma parfumé, apprécié pour sa couleur et sa profondeur en cuisine.",
    origin: "Inde.",
    storage: "A conserver au sec et à l'abri de l'humidité.",
    availability: "Disponible selon arrivage.",
    orderNote: "Produit vendu au kilo. Indiquez le poids souhaite avant l'ajout au panier.",
    tip: "Très utile pour assaisonner riz, sauces et marinades."
  },
  {
    id: "aubergine-blanc",
    name: "Aubergine blanche",
    category: "Légumes",
    priceValue: 6.5,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/Fruits jaunes sur fond blanc.png",
    description: "Aubergine blanche douce, ideale dans les sauces, les gratins et les plats mijotes.",
    origin: "Sénégal.",
    storage: "A conserver dans le bac a legumes du refrigerateur.",
    availability: "Disponible selon arrivage.",
    orderNote: "Produit vendu au kilo. Indiquez le poids souhaite avant l'ajout au panier.",
    tip: "Sa texture souple convient très bien aux cuissons lentes."
  },
  {
    id: "aubergine-gros",
    name: "Aubergine gros",
    category: "Légumes",
    priceValue: 6.5,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/Aubergine vert.png",
    description: "Aubergines en sachet, pratiques pour préparer rapidement un repas familial.",
    origin: "Sénégal.",
    storage: "A conserver au frais et a cuisiner rapidement.",
    availability: "Disponible selon le stock du jour.",
    orderNote: "Produit vendu au sachet. Choisissez le nombre souhaite avant l'ajout au panier.",
    tip: "Convient bien aux sauces, purées ou preparations maison."
  },

  {
    id: "baton-de-manioc",
    name: "Bâton de manioc",
    category: "Épicerie",
    priceValue: 1.2,
    unitMode: "count",
    unitLabel: "bâton",
    image: "images/baton de manioc.webp",
    description: "Baton de manioc traditionnel, ideal en accompagnement de sauces et plats cuisines.",
    origin: "Cameroun.",
    storage: "A conserver au frais et a consommer rapidement après achat.",
    availability: "Disponible selon le stock en boutique.",
    orderNote: "Produit vendu à l'unité.",
    tip: "Très utile pour accompagner poisson, viande ou sauce pimentee."
  },
  {
    id: "macabo-cameroun",
    name: "Macabo Cameroun",
    origin: "Cameroun.",
    category: "Tubercules",
    priceValue: 5.9,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/macabo cameroun.webp",
    description: "Tubercule apprécié en accompagnement ou dans les plats mijotés.",
    storage: "A conserver dans un endroit sec et tempéré.",
    availability: "Disponible selon arrivage.",
    orderNote: "Produit vendu au kilo. Indiquez le poids souhaite avant l'ajout au panier.",
    tip: "Très utile pour diversifier les accompagnements."
  },
  {
    id: "taro",
    name: "Taro",
    origin: "amérique du sud.",
    category: "Tubercules",
    priceValue: 5.9,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/Taro.png",
    description: "Tubercule apprécié en accompagnement ou dans les plats mijotés.",
    storage: "A conserver dans un endroit sec et tempéré.",
    availability: "Disponible selon arrivage.",
    orderNote: "Produit vendu au kilo. Indiquez le poids souhaite avant l'ajout au panier.",
    tip: "Très utile pour diversifier les accompagnements."
  },
  {
    id: "patate-douce-rose",
    name: "Patate douce rose",
    category: "Tubercules",
    priceValue: 2.99,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/Patate douce rose.png",
    description: "Patate douce rose légèrement sucré, très bonne au four, a la vapeur ou en purée.",
    origin: "Afrique de l'Ouest.",
    storage: "A conserver dans un endroit sec.",
    availability: "Disponible selon arrivage.",
    orderNote: "Produit vendu au kilo.",
    tip: "Donne une texture douce et généreuse."
  },
  {
    id: "patate-douce-blanche",
    name: "Patate douce blanche",
    category: "Tubercules",
    priceValue: 4.9,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/Patates douces dans une caisse en carton.png",
    description: "Patate douce blanche nourrissante, facile à cuire au four, a la vapeur ou en purée.",
    origin: "Afrique de l'Ouest.",
    storage: "A conserver dans un endroit sec, frais et ventile.",
    availability: "Disponible selon arrivage.",
    orderNote: "Produit vendu au kilo. Indiquez le poids souhaite avant l'ajout au panier.",
    tip: "Très bonne en accompagnement ou en plat complet."
  },
  {
    id: "igname-ghana",
    name: "Igname Ghana",
    category: "Tubercules",
    priceValue: 3.29,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/igname.png",
    description: "Igname du Ghana, incontournable pour de nombreux plats consistants et traditionnels.",
    origin: "Ghana.",
    storage: "A conserver dans un endroit sec et bien aere.",
    availability: "Disponible selon arrivage.",
    orderNote: "Produit vendu au kilo. Indiquez le poids souhaite avant l'ajout au panier.",
    tip: "Très pratique pour bouillir, frire ou transformer en purée."
  },
  {
    id: "igname-brésil",
    name: "Igname Brésil",
    category: "Tubercules",
    priceValue: 3.29,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/igname brésil.png",
    description: "Igname du Brésil, incontournable pour de nombreux plats consistants et traditionnels.",
    origin: "Brésil.",
    storage: "A conserver dans un endroit sec et bien aere.",
    availability: "Disponible selon arrivage.",
    orderNote: "Produit vendu au kilo. Indiquez le poids souhaite avant l'ajout au panier.",
    tip: "Très pratique pour bouillir, frire ou transformer en purée."
  },
  {
    id: "igname-cameroun",
    name: "Igname Cameroun",
    category: "Tubercules",
    priceValue: 4,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/igname cameroun.jpg",
    description: "Igname du Cameroun, savoureuse et pratique pour des plats consistants.",
    origin: "Cameroun.",
    storage: "A conserver dans un endroit sec.",
    availability: "Disponible selon arrivage.",
    orderNote: "Produit vendu au kilo. Indiquez le poids souhaite avant l'ajout au panier.",
    tip: "Peut être bouillie, frite ou transformée selon l'envie."
  },
  {
    id: "dachine",
    name: "Dachine",
    category: "Tubercules",
    priceValue: 5.9,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/DACHINE.webp",
    description: "Tubercule nourrissant, pratique pour les sauces, plats cuisines et accompagnements.",
    origin: "Afrique de l'Ouest.",
    storage: "A conserver dans un endroit sec et tempéré.",
    availability: "Disponible selon arrivage.",
    orderNote: "Produit vendu au kilo. Indiquez le poids souhaite avant l'ajout au panier.",
    tip: "Très utile pour les recettes traditionnelles."
  },
  {
    id: "manioc",
    name: "Manioc",
    category: "Tubercules",
    priceValue: 4.5,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/Manioc.png",
    description: "Manioc frais polyvalent, utilise dans de nombreuses recettes traditionnelles.",
    origin: "Afrique de l'Ouest.",
    storage: "A conserver au frais si possible et a utiliser rapidement.",
    availability: "Disponible selon arrivage.",
    orderNote: "Produit vendu au kilo.",
    tip: "A cuire ou transformer selon votre recette."
  },
  {
    id: "gombo-frais",
    name: "Gombo frais",
    category: "Légumes",
    priceValue: 8.9,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/Gombo.png",
    description: "Gombo frais, apprécié pour épaissir les sauces et apporter une texture specifique.",
    origin: "Togo.",
    storage: "A conserver au frais et a consommer rapidement.",
    availability: "Disponible selon saison.",
    orderNote: "Produit vendu au kilo. Indiquez le poids souhaite avant l'ajout au panier.",
    tip: "Peut être cuit entier, coupe ou mixe selon la recette."
  },
  {
    id: "piment-antillais",
    name: "Piment antillais",
    category: "Épices",
    priceValue: 22,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/piment-antillais.png",
    description: "Piment antillais très parfumé,très demandé du grand public.",
    origin: "Martinique.",
    storage: "A conserver au frais ou au sec selon l'état du produit.",
    availability: "Disponible selon arrivage.",
    orderNote: "Produit vendu au kilo.",
    tip: "Apporte beaucoup de caractère a une sauce ou une marinade."
  },
  {
    id: "piment-antillais-sachet",
    name: "Sachet de piments antillais",
    category: "Épices",
    priceValue: 1,
    unitMode: "count",
    unitLabel: "sachet",
    image: "images/piment-sachet-antillais.png",
    description: "Piments antillais frais conditionnés en petit sachet, prêts à relever vos préparations.",
    origin: "Martinique.",
    storage: "À conserver au frais et à manipuler avec précaution.",
    availability: "Disponible selon arrivage.",
    orderNote: "Produit vendu au sachet. Choisissez le nombre souhaité avant l'ajout au panier.",
    tip: "Un seul piment peut suffire pour parfumer une sauce ou un plat mijoté."
  },
  {
    id: "piment-vegetarien",
    name: "Piment végétarien",
    category: "Épices",
    priceValue: 32,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/piment végétarien.webp",
    description: "Piment végétarien très parfumé, utile pour donner du goût sans force excessive.",
    origin: "Martinique.",
    storage: "A conserver au frais.",
    availability: "Disponible selon arrivage.",
    orderNote: "Produit vendu au kilo. Indiquez le poids souhaite avant l'ajout au panier.",
    tip: "Idéal pour parfumer sauces et plats mijotés."
  },
  {
    id: "piment-oiseau",
    name: "Piment oiseau",
    category: "Épices",
    priceValue: 15,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/piment oiseau.png",
    description: "Petit piment très puissant pour relever les plats avec intensité.",
    origin: "Egypte.",
    storage: "A conserver au frais ou à faire sécher.",
    availability: "Disponible selon arrivage.",
    orderNote: "Produit vendu au kilo. Indiquez le poids souhaite avant l'ajout au panier.",
    tip: "A utiliser en petite quantité."
  },
  {
    id: "piment-poudre",
    name: "Piment poudre",
    category: "Épices",
    priceValue: 5,
    unitMode: "count",
    unitLabel: "sachet",
    image: "images/Piment poudre.png",
    description: "Piment en poudre sympa pour les plats épicés.",
    origin: "Cote d'Ivoire.",
    storage: "A conserver au frais ou à faire sécher.",
    availability: "Disponible selon arrivage.",
    orderNote: "Produit vendu au sachet. Indiquez le nombre souhaite avant l'ajout au panier.",
    tip: "A utiliser en petite quantité."
  },
  {
    id: "canne-a-sucre",
    name: "Canne à sucre",
    priceValue: 7.5,
    category: "Fruits",
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/Canne à sucre.jpg",
    description: "Canne à sucre fraîche, naturellement sucrée, agréable à mâcher ou à presser.",
    origin: "Afrique de l'Ouest.",
    storage: "A conserver dans un endroit frais.",
    availability: "Disponible selon le stock du jour.",
    orderNote: "Produit vendu au kilo. Indiquez le poids souhaite avant l'ajout au panier.",
    tip: "Peut être coupée en morceaux pour une dégustation simple."
  },
  {
    id: "christophine-blanche",
    name: "Christophine blanche",
    category: "Légumes",
    priceValue: 3.9,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/christophine blanche.jpg",
    description: "Christophine blanche tendre, facile a intégrer dans des gratins ou accompagnements.",
    origin: "Afrique de l'Ouest.",
    storage: "A conserver au frais ou dans un endroit tempéré.",
    availability: "Disponible selon arrivage.",
    orderNote: "Produit vendu au kilo. Indiquez le poids souhaite avant l'ajout au panier.",
    tip: "Très appréciée pour les recettes douces et légumes farcis."
  },
  {
    id: "christophine-vert",
    name: "Christophine verte",
    category: "Légumes",
    priceValue: 3,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/Christophine.png",
    description: "Christophine verte au goût délicat, appréciée en gratin ou cuisson douce.",
    origin: "Afrique de l'Ouest.",
    storage: "A conserver dans un endroit frais.",
    availability: "Disponible selon arrivage.",
    orderNote: "Produit vendu au kilo. Indiquez le poids souhaite avant l'ajout au panier.",
    tip: "Se marie bien avec herbes et sauce cremeuse."
  },
  {
    id: "ail",
    name: "Ail",
    category: "Épices",
    priceValue: 1.5,
    unitMode: "count",
    unitLabel: "paquet",
    image: "images/ail.png",
    description: "Ail parfumé, utile pour relever sauces, viandes, legumes et marinades.",
    origin: "Afrique de l'Ouest.",
    storage: "A conserver dans un endroit sec et aere.",
    availability: "Disponible selon le stock du jour.",
    orderNote: "Produit vendu au paquet.",
    tip: "Base très utile pour une cuisine quotidienne."
  },
  {
    id: "ail-pele",
    name: "Ail pelé",
    category: "Épices",
    priceValue: 7.5,
    unitMode: "count",
    unitLabel: "sachet",
    image: "images/ail-pele.png",
    description: "Ail déjà pelé et prêt à utiliser pour gagner du temps en cuisine.",
    origin: "Origine selon arrivage.",
    storage: "À conserver au frais et à consommer selon les indications de l'emballage.",
    availability: "Disponible selon le stock du jour.",
    orderNote: "Produit vendu au sachet.",
    tip: "Pratique pour préparer rapidement sauces, marinades et plats mijotés."
  },
  {
    id: "cives",
    name: "Cives",
    category: "Épices",
    priceValue: 1.9,
    unitMode: "count",
    unitLabel: "pièce",
    image: "images/cives.png",
    description: "Cives fraiches, tres utiles pour assaisonner sauces, legumes et grillades.",
    origin: "Afrique de l'Ouest.",
    storage: "A conserver au frais dans un linge legerement humide.",
    availability: "Disponible selon le stock du jour.",
    orderNote: "Produit vendu a la piece. Choisissez le nombre souhaite avant l'ajout au panier.",
    tip: "Ajoute une note fraiche et parfume la cuisine du quotidien."
  },
  {
    id: "citron-vert",
    name: "Citron vert",
    category: "Fruits",
    priceValue: 5.5,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/citron.png",
    description: "Citron vert frais, ideal pour jus, marinades, desserts et boissons.",
    origin: "Afrique de l'Ouest.",
    storage: "A conserver au frais pour garder la fraicheur.",
    availability: "Disponible selon arrivage.",
    orderNote: "Produit vendu au kilo. Indiquez le poids souhaite avant l'ajout au panier.",
    tip: "Apporte une touche vive aux plats et boissons maison."
  },
  {
    id: "citronnelle",
    name: "Citronnelle",
    category: "Épices",
    priceValue: 10,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/citronnelle.png",
    description: "Citronnelle fraiche, utile pour infusions, bouillons et plats parfumes.",
    origin: "Afrique de l'Ouest.",
    storage: "A conserver au frais ou a congeler en petite quantite.",
    availability: "Disponible selon arrivage.",
    orderNote: "Produit vendu au kilo. Indiquez le poids souhaite avant l'ajout au panier.",
    tip: "Parfaite pour les infusions et les recettes parfumees."
  },
  {
    id: "papaye",
    name: "Papaye",
    category: "Fruits",
    priceValue: 5.9,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/papaye.png",
    description: "Papaye douce et fondante, agréable nature, en smoothie ou en dessert.",
    origin: "Afrique de l'Ouest.",
    storage: "A temperature ambiante jusqu'a maturation, puis au frais.",
    availability: "Disponible selon arrivage.",
    orderNote: "Produit vendu au kilo. Indiquez le poids souhaite avant l'ajout au panier.",
    tip: "Peut etre servie fraiche ou mixee."
  },
  {
    id: "papaye verte",
    name: "Papaye verte",
    category: "Fruits",
    priceValue: 5.9,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/papaye verte.png",
    description: "Papaye douce et fondante, agréable nature, en smoothie ou en dessert.",
    origin: "Afrique de l'Ouest.",
    storage: "A temperature ambiante jusqu'a maturation, puis au frais.",
    availability: "Disponible selon arrivage.",
    orderNote: "Produit vendu au kilo. Indiquez le poids souhaite avant l'ajout au panier.",
    tip: "Peut etre servie fraiche ou mixee."
  },
  {
    id: "poudre-de-baobab",
    name: "Poudre de baobab",
    category: "Épicerie",
    priceValue: 6,
    unitMode: "count",
    unitLabel: "boîte",
    image: "images/poudre-baobab.png",
    description: "Poudre acidulée pour jus, desserts, smoothies et préparations maison.",
    origin: "Afrique de l'Ouest.",
    storage: "A conserver au sec et bien fermée.",
    availability: "Disponible selon le stock du jour.",
    orderNote: "Produit vendu à la boîte. Choisissez le nombre souhaite avant l'ajout au panier.",
    tip: "Peut être ajoutée à l'eau, au yaourt ou à une boisson maison."
  },
  {
    id: "comcombreamere",
    name: "Concombre amer",
    category: "Légumes",
    priceValue: 2,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/comcombreamere.webp",
    description: "Légume exotique au goût marqué, recherché pour certaines recettes traditionnelles.",
    origin: "Afrique de l'Ouest.",
    storage: "A conserver au frais.",
    availability: "Disponible selon arrivage.",
    orderNote: "Produit vendu au kilo. Indiquez le poids souhaite avant l'ajout au panier.",
    tip: "Son profil affirme le rend très spécifique en cuisine."
  },
  {
    id: "gari",
    name: "Gari",
    category: "Épicerie",
    priceValue: 3.5,
    unitMode: "count",
    unitLabel: "paquet",
    image: "images/Gari-du-Togo-semoule-de-manioc-.jpg",
    description: "Semoule de manioc très pratique, utile au quotidien dans plusieurs preparations.",
    origin: "Togo.",
    storage: "A conserver au sec et bien refermé.",
    availability: "Disponible selon stock.",
    orderNote: "Produit vendu au paquet. Choisissez le nombre souhaite avant l'ajout au panier.",
    tip: "Peut être servi seul, hydrate ou accompagne d'une sauce."
  },
  {
    id: "haricot",
    name: "Haricot",
    category: "Épicerie",
    priceValue: 5,
    unitMode: "count",
    unitLabel: "paquet",
    image: "images/haricot.png",
    description: "Haricots secs pour sauces, plats mijotes et accompagnements nourrissants.",
    origin: "Togo.",
    storage: "A conserver au sec.",
    availability: "Disponible selon stock.",
    orderNote: "Produit vendu au paquet. Choisissez le nombre souhaite avant l'ajout au panier.",
    tip: "Base simple et utile dans beaucoup de cuisines."
  },
  {
    id: "kombava",
    name: "Kombava",
    category: "Fruits",
    priceValue: 2,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/kombava.webp",
    description: "Agrume très parfumé, utile pour relever sauces, plats et desserts.",
    origin: "Inde.",
    storage: "A conserver au frais.",
    availability: "Disponible selon arrivage.",
    orderNote: "Produit vendu au kilo. Indiquez le poids souhaite avant l'ajout au panier.",
    tip: "Son zeste et son parfum sont très recherchés."
  },
  {
    id: "morrue",
    name: "Morrue",
    category: "Poissonnerie",
    priceValue: 19.9,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/Morrue.png",
    description: "Morrue savoureuse pour accras, sauces, gratins et plats cuisines.",
    origin: "Portugal.",
    storage: "A conserver au frais.",
    availability: "Disponible selon stock.",
    orderNote: "Produit vendu au kilo.",
    tip: "A déssaler ou préparer selon votre recette."
  },
  {
    id: "harang",
    name: "Harang",
    category: "Poissonnerie",
    priceValue: 2,
    unitMode: "count",
    unitLabel: "pièce",
    image: "images/harang.jpg",
    description: "Poisson au goût prononcé, pratique pour sauces et recettes traditionnelles.",
    origin: "Afrique de l'Ouest.",
    storage: "A conserver au frais.",
    availability: "Disponible selon stock.",
    orderNote: "Produit vendu à la pièce. Choisissez le nombre souhaite avant l'ajout au panier.",
    tip: "Donne du caractère à de nombreux plats."
  },
  {
    id: "pate-arachide",
    name: "Pâte arachide",
    category: "Épicerie",
    priceValue: 6.9,
    unitMode: "count",
    unitLabel: "pot",
    image: "images/pate-arachide.png",
    description: "Pâte onctueuse, idéale pour sauces, mafes et recettes gourmandes.",
    origin: "Afrique de l'Ouest.",
    storage: "A conserver bien fermée, au sec ou au frais après ouverture.",
    availability: "Disponible selon stock.",
    orderNote: "Produit vendu au pot. Choisissez le nombre souhaite avant l'ajout au panier.",
    tip: "Texture pratique et riche en goût."
  },
  {
    id: "sauce-graine",
    name: "Sauce graine",
    category: "Épicerie",
    priceValue: 7,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/Sauce graine.png",
    description: "Base savoureuse pour préparer une sauce graine riche et traditionnelle.",
    origin: "Afrique de l'Ouest.",
    storage: "A conserver selon l'état du produit, au frais si nécessaire.",
    availability: "Disponible selon stock.",
    orderNote: "Produit vendu au kilo. Indiquez le poids souhaite avant l'ajout au panier.",
    tip: "Très pratique pour gagner du temps en cuisine."
  },
  {
    id: "goussi",
    name: "Goussi",
    category: "Épicerie",
    priceValue: 8,
    unitMode: "count",
    unitLabel: "sachet",
    image: "images/goussi.png",
    description: "Goussi pratique pour préparer des sauces et recettes traditionnelles riches en goût.",
    origin: "Togo.",
    storage: "A conserver au sec, dans un contenant bien ferme.",
    availability: "Disponible selon stock.",
    orderNote: "Produit vendu au sachet. Choisissez le nombre souhaite avant l'ajout au panier.",
    tip: "Très utile pour les sauces maison et certaines preparations traditionnelles."
  },
  {
    id: "rondelle-graine",
    name: "Rondelle graine",
    category: "Épices",
    priceValue: 5,
    unitMode: "count",
    unitLabel: "sachet",
    image: "images/rondelle-graine.png",
    description: "Épice camerounaise en graines, utilisée pour parfumer différentes recettes traditionnelles.",
    origin: "Cameroun.",
    storage: "À conserver dans un endroit sec, frais et à l'abri de la lumière.",
    availability: "Disponible selon le stock du jour.",
    orderNote: "Produit vendu au sachet. Choisissez le nombre souhaité avant l'ajout au panier.",
    tip: "À doser progressivement selon la recette et l'intensité aromatique souhaitée."
  },
  {
    id: "clou-de-girofle",
    name: "Clou de girofle",
    category: "Épices",
    priceValue: 8,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/Girofle.png",
    description: "Epice puissante, utile pour infusions, marinades et plats epices.",
    origin: "Madagascar.",
    storage: "A conserver dans un endroit sec.",
    availability: "Disponible selon stock.",
    orderNote: "Produit vendu au kilo. Indiquez le poids souhaite avant l'ajout au panier.",
    tip: "Son parfum est très marque."
  },
  {
    id: "baton-de-cannelle",
    name: "Bâton de cannelle",
    category: "Épices",
    priceValue: 6,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/cannelle.webp",
    description: "Cannelle en baton pour infusions, desserts, plats mijotés et boissons.",
    origin: "Sri Lanka.",
    storage: "A conserver au sec.",
    availability: "Disponible selon stock.",
    orderNote: "Produit vendu au kilo. Indiquez le poids souhaite avant l'ajout au panier.",
    tip: "Très utile pour les boissons et desserts maison."
  },
  {
    id: "moringa",
    name: "Moringa feuille",
    category: "Épicerie",
    priceValue: 9,
    unitMode: "count",
    unitLabel: "sachet",
    image: "images/moringa feuille.png",
    description: "Feuilles de moringa séchées, proposées en sachet pour les préparations maison.",
    origin: "Afrique de l'Ouest.",
    storage: "À conserver au sec, dans un sachet bien refermé.",
    availability: "Disponible selon stock.",
    orderNote: "Produit vendu au sachet. Choisissez le nombre souhaité avant l'ajout au panier.",
    tip: "À utiliser selon vos habitudes de préparation."
  },
  {
    id: "tamarin",
    name: "Tamarin",
    category: "Épicerie",
    priceValue: 4.9,
    unitMode: "count",
    unitLabel: "sachet",
    image: "images/tamarin.png",
    description: "Tamarin dénoyauté au goût acidulé, proposé en sachet pour les boissons, sauces et recettes maison.",
    origin: "Thaïlande.",
    storage: "À conserver dans un endroit frais et sec après ouverture.",
    availability: "Disponible selon stock.",
    orderNote: "Produit vendu au sachet. Choisissez le nombre souhaité avant l'ajout au panier.",
    tip: "Peut être utilisé dans une boisson, une sauce ou une préparation sucrée."
  },
  {
    id: "poudre-moringa",
    name: "Poudre de moringa",
    category: "Épicerie",
    priceValue: 9,
    unitMode: "count",
    unitLabel: "sachet",
    image: "images/poudre-moringa.png",
    description: "Poudre de feuilles de moringa conditionnée en sachet, facile à intégrer aux préparations habituelles.",
    origin: "Afrique de l'Ouest.",
    storage: "À conserver au sec, dans un emballage bien refermé.",
    availability: "Disponible selon stock.",
    orderNote: "Produit vendu au sachet. Choisissez le nombre souhaité avant l'ajout au panier.",
    tip: "Respectez les indications présentes sur l'emballage du produit."
  },
  {
    id: "feuilles-laurier",
    name: "Feuilles de laurier",
    category: "Épicerie",
    priceValue: 10,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/feuilles-laurier.png",
    description: "Feuilles de laurier séchées pour parfumer les sauces, bouillons et plats mijotés.",
    origin: "Selon arrivage.",
    storage: "À conserver au sec, à l'abri de la lumière.",
    availability: "Disponible selon stock.",
    orderNote: "Produit vendu au kilo. Indiquez le poids souhaité avant l'ajout au panier.",
    tip: "Quelques feuilles suffisent généralement pour parfumer une préparation."
  },
  {
    id: "attieke",
    name: "Attieke",
    category: "Épicerie",
    priceValue: 5,
    unitMode: "count",
    unitLabel: "boule",
    image: "images/attiéké.webp",
    description: "Semoule de manioc ivoirienne, legère et pratique en accompagnement.",
    origin: "Côte d'Ivoire.",
    storage: "A conserver au frais si nécessaire.",
    availability: "Disponible selon stock.",
    orderNote: "Produit vendu a la boule. Choisissez le nombre souhaite avant l'ajout au panier.",
    tip: "Très bonne avec poisson, viande ou légumes."
  },
  {
    id: "Fruit à pain",
    name: "Fruit à pain",
    category: "Fruits",
    priceValue: 6,
    unitMode: "weight",
    unitLabel: "kg",
    image: "images/Fruit à pain.webp",
    description: "Fruit exotique de Martinique, idéal pour les desserts et les smoothies.",
    origin : "martinique.",
    storage: "A conserver au frais si nécessaire.",
    availability: "Disponible selon stock.",
    orderNote: "Produit vendu au kilo. Indiquez le poids souhaite avant l'ajout au panier.",
    tip: "Très utile pour les desserts et smoothies."
  },
  {
    id: "bissap-rouge",
    name: "Bissap rouge",
    category: "Épicerie",
    priceValue: 4,
    unitMode: "count",
    unitLabel: "sachet",
    image: "images/bissap-rouge.png",
    description: "Fleurs d'hibiscus séchées, idéales pour préparer une boisson au bissap maison.",
    origin: "Afrique de l'Ouest.",
    storage: "À conserver dans un endroit sec, frais et à l'abri de la lumière.",
    availability: "Disponible selon le stock du jour.",
    orderNote: "Produit vendu au sachet.",
    tip: "À faire infuser puis à parfumer selon vos goûts avec du gingembre, de la menthe ou du citron."
  },
  {
    id: "bissap-benin",
    name: "Bissap rouge du Bénin",
    category: "Épicerie",
    priceValue: 15,
    unitMode: "count",
    unitLabel: "sachet",
    image: "images/bissap-benin.png",
    description: "Fleurs d'hibiscus séchées originaires du Bénin, prêtes à infuser pour préparer du bissap.",
    origin: "Bénin.",
    storage: "À conserver dans un endroit sec, frais et à l'abri de la lumière.",
    availability: "Disponible selon le stock du jour.",
    orderNote: "Produit vendu au sachet.",
    tip: "À infuser puis à servir frais, avec la quantité de sucre et les aromates de votre choix."
  },
  {
    id: "bissap-rouge-500g",
    name: "Bissap rouge 500 g",
    category: "Épicerie",
    priceValue: 8,
    unitMode: "count",
    unitLabel: "sachet",
    image: "images/bissap-rouge-500g.png",
    description: "Sachet de 500 g de fleurs d'hibiscus séchées pour préparer du bissap maison.",
    origin: "Emballé au Bénin.",
    storage: "À conserver dans un endroit sec, frais et à l'abri de la lumière.",
    availability: "Disponible selon le stock du jour.",
    orderNote: "Produit vendu en sachet de 500 g.",
    tip: "À infuser puis à servir frais avec du gingembre, de la menthe ou du citron."
  },
  {
    id: "Noix de cola",
    name: "Noix de cola",
    category: "Épicerie",
    priceValue: 0.20,
    unitMode: "count",
    unitLabel: "piece",
    image: "images/noix de cola.png",
    description: "Noix de cola séchées, riches en nutriments et en antioxydants.",
    origin: "Afrique de l'Ouest.",
    storage: "À conserver dans un endroit sec, frais et à l'abri de la lumière.",
    availability: "Disponible selon le stock du jour.",
    orderNote: "Produit vendu au sachet.",
    tip: "À ajouter à vos smoothies ou à cuisiner comme un légume."
  },
  {
    id: "Petit cola",
    name: "Petit cola",
    category: "Épicerie",
    priceValue: 0.15,
    unitMode: "count",
    unitLabel: "piece",
    image: "images/petit-cola.png",
    description: "Petit cola séché, idéal pour préparer une boisson rafraîchissante.",
    origin: "Afrique de l'Ouest.",
    storage: "À conserver dans un endroit sec, frais et à l'abri de la lumière.",
    availability: "Disponible selon le stock du jour.",
    orderNote: "Produit vendu au sachet.",
    tip: "À servir frais avec un peu de sucre et des glaçons."
  },
  {
    id: "beurre de karité",
    name: "Beurre de karité",
    category: "Épicerie",
    priceValue: 5,
    unitMode: "count",
    unitLabel: "piece",
    image: "images/beurre-de-karite.png",
    description: "Beurre de karité pur, idéal pour l'hygiène et la beauté.",
    origin: "Afrique de l'Ouest.",
    storage: "À conserver dans un endroit sec, frais et à l'abri de la lumière.",
    availability: "Disponible selon le stock du jour.",
    orderNote: "Produit vendu au sachet.",
    tip: "À utiliser pour hydrater la peau ou comme ingrédient dans les soins du corps."
  }
];

// Construit l'URL de la fiche detaillee a partir de l'identifiant produit.
function productUrl(product) {
  return `produit.html?id=${encodeURIComponent(product.id)}`;
}
// Informations globales du site et cles de stockage du navigateur.
const siteInfo = {
  brand: "Capri Exo",
  whatsappNumber: "33600000000",
  keys: {
    favorites: "capriExoFavoris",
    favoritesIndex: "capriExoFavorisIndex",
    cart: "capriExoPanier",
    client: "capriExoClient",
    clients: "capriExoClients",
    reviews: "capriExoAvis",
    messages: "capriExoMessages",
    orders: "capriExoCommandes",
    orderDraft: "capriExoCommandeBrouillon",
    productCatalog: "capriExoProduits",
    inventory: "capriExoInventaire"
  },
  backend: {
    enabled: true,
    baseUrl: "http://127.0.0.1:8000/api",
    mode: "local-first",
    version: "prep-v2",
    resources: ["products", "inventory", "clients", "favorites", "orders", "reviews", "messages"]
  }
};

const markets = [
  {
    id: "cergy",
    name: "Marché de Cergy",
    city: "Cergy-Saint-Christophe",
    stand: "Allée centrale, côté fruits et légumes",
    schedule: "Mercredi et Samedi de 8h à 13h30",
    image: "images/marche-cergy.jpg",
    imageTitle: "Stand Capri Exo au marché de Cergy",
    summary: "Un marché de matinée pratique pour retrouver une sélection de produits exotiques, de fruits, de légumes et d'épicerie dans une ambiance vivante et familiale.",
    note: "Point de repère conseillé : repérez le stand près des arrivages frais et des produits du quotidien. Cet emplacement est idéal pour un passage rapide en semaine ou le samedi matin."
  },
  {
    id: "mantes-la-jolie",
    name: "Marché du Val Fourré",
    city: "Mantes-la-Jolie",
    stand: "Zone commerçante principale, à proximité des stands d'épicerie",
    schedule: "Mardi et Vendredi de 11h à 18h30",
    image: "images/marche-mantes-la-jolie.jpg",
    imageTitle: "Ajoute ici une photo du stand de Mantes-la-Jolie",
    summary: "Un deuxième point de présence pensé pour les clients qui souhaitent retrouver Capri Exo plus tard dans la journée, avec une sélection adaptée aux achats du quotidien.",
    note: "Ce marché permet de passer après la matinée, de poser une question sur un produit et de retrouver plus facilement certains articles selon les arrivages."
  },
];

// Etat UI partage entre les differentes pages.
let currentCategoryFilter = "all";
let currentFavoritesOnly = false;
let currentSortOption = "default";
let currentAvailabilityFilter = "all";
let currentUnitModeFilter = "all";
let currentTagFilter = "all";
let pageTransitionRunning = false;
let toastTimer = 0;
let revealObserver = null;

