# Generated by Django 6.0.5 on 2026-06-30 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='market_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(default='received', max_length=30),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='delivery_mode',
            field=models.CharField(default='pickup', max_length=30),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='frontend_client_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='frontend_order_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='payment_mode',
            field=models.CharField(default='shop', max_length=30),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='payment_status',
            field=models.CharField(default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='pickup_market',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='pickup_slot',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='market_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product'),
        ),
    ]
